// <auto-generated />
using System;
using FinalProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220322022710_creatDB")]
    partial class creatDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Entities.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("dateTime");

                    b.Property<int>("luongTongId")
                        .HasColumnType("int");

                    b.Property<string>("trangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("luongTongId");

                    b.ToTable("chamCongs");
                });

            modelBuilder.Entity("FinalProject.Entities.DonXinNghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("dateTime");

                    b.Property<string>("lyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lyDoTuChoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("soNgayNghi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("nhanVienId");

                    b.ToTable("donXinNghiPheps");
                });

            modelBuilder.Entity("FinalProject.Entities.DuAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("luongThuong")
                        .HasColumnType("float");

                    b.Property<string>("tenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("duAns");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongKhauTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("dateTime");

                    b.Property<int>("luongTongId")
                        .HasColumnType("int");

                    b.Property<int>("soGioMuon")
                        .HasColumnType("int");

                    b.Property<int>("soNgayMuon")
                        .HasColumnType("int");

                    b.Property<double>("tienKhauTru")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("luongTongId");

                    b.ToTable("luongKhauTrus");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongLamThem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("dateTime");

                    b.Property<int>("duAnId")
                        .HasColumnType("int");

                    b.Property<int>("luongTongId")
                        .HasColumnType("int");

                    b.Property<int>("soGioLam")
                        .HasColumnType("int");

                    b.Property<double>("tienThuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("duAnId");

                    b.HasIndex("luongTongId");

                    b.ToTable("luongLamThems");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongTong", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("dateTime");

                    b.Property<double>("luongCung")
                        .HasColumnType("float");

                    b.Property<double>("luongKhauTru")
                        .HasColumnType("float");

                    b.Property<double>("luongLamThem")
                        .HasColumnType("float");

                    b.Property<double>("luongTong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("luongTongs");
                });

            modelBuilder.Entity("FinalProject.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cMND")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("chucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sDT")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("taiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("FinalProject.Entities.SuKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ngayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThuc");

                    b.Property<string>("noiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("suKiens");
                });

            modelBuilder.Entity("FinalProject.Entities.ChamCong", b =>
                {
                    b.HasOne("FinalProject.Entities.LuongTong", "Luong")
                        .WithMany("chamCongs")
                        .HasForeignKey("luongTongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("FinalProject.Entities.DonXinNghiPhep", b =>
                {
                    b.HasOne("FinalProject.Entities.NhanVien", "NhanVien")
                        .WithMany("donXinNghiPheps")
                        .HasForeignKey("nhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongKhauTru", b =>
                {
                    b.HasOne("FinalProject.Entities.LuongTong", "Luong")
                        .WithMany("luongKhauTrus")
                        .HasForeignKey("luongTongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongLamThem", b =>
                {
                    b.HasOne("FinalProject.Entities.DuAn", null)
                        .WithMany("luongLamThems")
                        .HasForeignKey("duAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Entities.LuongTong", "Luong")
                        .WithMany("luongLamThems")
                        .HasForeignKey("luongTongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongTong", b =>
                {
                    b.HasOne("FinalProject.Entities.NhanVien", "NhanVien")
                        .WithOne("Luong")
                        .HasForeignKey("FinalProject.Entities.LuongTong", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FinalProject.Entities.DuAn", b =>
                {
                    b.Navigation("luongLamThems");
                });

            modelBuilder.Entity("FinalProject.Entities.LuongTong", b =>
                {
                    b.Navigation("chamCongs");

                    b.Navigation("luongKhauTrus");

                    b.Navigation("luongLamThems");
                });

            modelBuilder.Entity("FinalProject.Entities.NhanVien", b =>
                {
                    b.Navigation("donXinNghiPheps");

                    b.Navigation("Luong");
                });
#pragma warning restore 612, 618
        }
    }
}
